<?php

namespace ContainerYTQ71AQ;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getItem3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.u1f_Ssc.App\Entity\Item' shared service.
     *
     * @return \App\Entity\Item
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.u1f_Ssc": it needs an instance of "App\\Entity\\Item" but this type has been excluded in "config/services.yaml".');
    }
}
