<?php

namespace ContainerBK3o7vl;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BjmKoETService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.bjmKoET' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bjmKoET'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\PostsController::addToCart' => ['privates', '.service_locator.J2r0Nrg', 'get_ServiceLocator_J2r0NrgService', true],
            'App\\Controller\\PostsController::cart' => ['privates', '.service_locator.J2r0Nrg', 'get_ServiceLocator_J2r0NrgService', true],
            'App\\Controller\\PostsController::catalogue' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PostsController::index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PostsController::itemDetail' => ['privates', '.service_locator.u1f_Ssc', 'get_ServiceLocator_U1fSscService', true],
            'App\\Controller\\PostsController::login_db' => ['privates', '.service_locator.sBSvV5M', 'get_ServiceLocator_SBSvV5MService', true],
            'App\\Controller\\PostsController::register' => ['privates', '.service_locator.sBSvV5M', 'get_ServiceLocator_SBSvV5MService', true],
            'App\\Controller\\PostsController::removeFromCart' => ['privates', '.service_locator.J2r0Nrg', 'get_ServiceLocator_J2r0NrgService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\PostsController:addToCart' => ['privates', '.service_locator.J2r0Nrg', 'get_ServiceLocator_J2r0NrgService', true],
            'App\\Controller\\PostsController:cart' => ['privates', '.service_locator.J2r0Nrg', 'get_ServiceLocator_J2r0NrgService', true],
            'App\\Controller\\PostsController:catalogue' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PostsController:index' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\PostsController:itemDetail' => ['privates', '.service_locator.u1f_Ssc', 'get_ServiceLocator_U1fSscService', true],
            'App\\Controller\\PostsController:login_db' => ['privates', '.service_locator.sBSvV5M', 'get_ServiceLocator_SBSvV5MService', true],
            'App\\Controller\\PostsController:register' => ['privates', '.service_locator.sBSvV5M', 'get_ServiceLocator_SBSvV5MService', true],
            'App\\Controller\\PostsController:removeFromCart' => ['privates', '.service_locator.J2r0Nrg', 'get_ServiceLocator_J2r0NrgService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\PostsController::addToCart' => '?',
            'App\\Controller\\PostsController::cart' => '?',
            'App\\Controller\\PostsController::catalogue' => '?',
            'App\\Controller\\PostsController::index' => '?',
            'App\\Controller\\PostsController::itemDetail' => '?',
            'App\\Controller\\PostsController::login_db' => '?',
            'App\\Controller\\PostsController::register' => '?',
            'App\\Controller\\PostsController::removeFromCart' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PostsController:addToCart' => '?',
            'App\\Controller\\PostsController:cart' => '?',
            'App\\Controller\\PostsController:catalogue' => '?',
            'App\\Controller\\PostsController:index' => '?',
            'App\\Controller\\PostsController:itemDetail' => '?',
            'App\\Controller\\PostsController:login_db' => '?',
            'App\\Controller\\PostsController:register' => '?',
            'App\\Controller\\PostsController:removeFromCart' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
