<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0sTnAQg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0sTnAQg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0sTnAQg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0sTnAQg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0sTnAQg\App_KernelDevDebugContainer([
    'container.build_hash' => '0sTnAQg',
    'container.build_id' => 'ca5db17f',
    'container.build_time' => 1741528568,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container0sTnAQg');
